### ISSUE TITLE
Bitcoin is primarily for illegal or anti-social purposes

### ISSUE THREAD

**Issue by GPFlljk** [owocki/adblock-to-bitcoin#5]
Why would I replace an advertisement for something that may actually be worth my time and money with one lie after another attempting to pump up the value of a valueless string of bits?

**Comment by moul** [comment]
![](http://cdn.meme.am/instances/58200766.jpg)

**Comment by owocki** [comment]
> Why would I replace an advertisement for something that may actually be worth my time and money with one lie after another attempting to pump up the value of a valueless string of bits?

Adblock-to-bitcoin only activates when an adblocker is in use (advertisements have already been blocked), therefore no user of the project is 'replacing advertisements'.  Only providing a use for the _dead_ real estate created by an adblocker.

As for the rest of the OPs conjecture about the value of bitcoin, it is outside of the scope of _adblock-to-bitcoin_, but for OP's benefit I'd suggest reading [here](http://www.coindesk.com/information/what-is-bitcoin/) or [here](http://www.investopedia.com/ask/answers/100314/why-do-bitcoins-have-value.asp).

**Comment by darkdarkdragon** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 0.15 ETH (103.82 USD @ $692.1/ETH) attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](http://localhost:8000/issue/owocki/adblock-to-bitcoin/5/522).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $0 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by andysavage** [comment]
@darkdarkdragon  thanks, this is a really great idea and sadly it has not worked for some time.  there's an error in the link http://localhost:8000/issue/owocki/adblock-to-bitcoin/5/522 and https://gitcoin.co/issue/ssue/owocki/adblock-to-bitcoin/5/522 gives a 'no funded issue found'.
